version: '3'
services:
  web:
    build: .
    container_name: lamp
    restart: always
    working_dir: /var/www
    volumes:
        - ./:/var/www:cached
    ports:
     - "80:80"
     - "443:443"

    
